name: db_vendor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  google_fonts: ^2.0.0
  get: ^4.0.0-nullsafety.2
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.3
  firebase_crashlytics: ^2.0.0
  get_storage: ^2.0.1
  introduction_screen: ^2.0.0
  permission_handler: ^6.1.1
  font_awesome_flutter: ^9.0.0
  pin_code_fields: ^7.0.0
  flappy_search_bar_fork: ^1.7.4
  carousel_slider: ^3.0.0
  image: ^3.0.2
  cached_network_image: ^3.0.0-nullsafety
  animations: ^2.0.0
  flutter_animation_progress_bar: ^2.0.0
  flutter_country_state: ^0.2.0
  google_maps_flutter: ^2.0.1
  google_place: ^0.4.0
  location: ^4.1.1
  firebase_database: ^6.1.2
  flutter_phoenix: ^1.0.0
  flutter_restart: ^0.0.3
  sms_autofill: ^1.3.1
  flutter_svg: ^0.21.0-nullsafety.0ur
  intl: ^0.17.0
  numberpicker: ^1.0.0
  flare_splash_screen: ^3.0.1
  flutter_rating_bar: ^4.0.0
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.4
  rubber: ^0.5.0
  pin_code_text_field: ^1.8.0
  country_code_picker: ^2.0.1
  html: ^0.15.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  smooth_star_rating: ^1.1.1
  flutter_cache: ^0.1.0
  flutter_launcher_icons: ^0.9.0
  animated_splash_screen: ^1.1.0
  syncfusion_flutter_pdfviewer: ^19.1.56-beta
  cloud_firestore: ^1.0.6
  flutter_snake_navigationbar: ^0.5.0
  url_launcher: ^6.0.3


flutter_icons: 
  android: true
  ios: true
  image_path: "assets/logo.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gifs/
    - assets/images/
    - assets/
    - assets/icons/
    - assets/docs/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
